services:
    nginx:
        image: ${DOCKER_IMAGE}
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
            - ./certbot/logs:/var/log/letsencrypt
            - ./dubna-hirudo-dist:/usr/share/nginx/html
            - ./define-click-dist:/usr/share/nginx/html/define-click
        depends_on:
            - certbot
        command: "nginx -g 'daemon off;'"
        restart: unless-stopped

    certbot:
        image: certbot/certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
            - ./certbot/logs:/var/log/letsencrypt
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        restart: unless-stopped

networks:
    default:
        name: my-server-nginx_default
        driver: bridge